x-node: &node
  image: postgres:13
  env_file: ".env"
  networks:
    - tbd-ddb

services:
  # backend:
  #   build: ./backend
  #   container_name: tbd-backend
  #   depends_on:
  #     master-node:
  #       condition: service_healthy
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - tbd-ddb

  master-node:
    <<: *node
    container_name: tbd-master-node
    volumes:
      - ./ddb/master_node:/docker-entrypoint-initdb.d
      # - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      # - ./ddb/master_node/custom_conf.conf:/etc/postgresql.conf
    # command: -c config_file=/etc/postgresql.conf
    ports:  
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres

  node-1:
    <<: *node
    container_name: tbd-node-1
    ports:
      - "5433:5432"
    volumes:
      - ./ddb/child_node/1_init_table_child_node.sql:/docker-entrypoint-initdb.d/1_init_table.sql
      - ./ddb/child_node/node_1/2_replicate_master_node.sql:/docker-entrypoint-initdb.d/2_replicate_master_node.sql
      - ./ddb/child_node/node_1/3_init_data.sql:/docker-entrypoint-initdb.d/3_init_data.sql
      # - ./init_db.sh:/docker-entrypoint-initdb.d/1_init_db.sh
    healthcheck:
      test: pg_isready -U postgres
    depends_on:
      - master-node

  node-2:
    <<: *node
    container_name: tbd-node-2
    ports:
      - "5434:5432"
    volumes:
      - ./ddb/child_node/1_init_table_child_node.sql:/docker-entrypoint-initdb.d/1_init_table.sql
      - ./ddb/child_node/node_2/2_replicate_master_node.sql:/docker-entrypoint-initdb.d/2_replicate_master_node.sql
      - ./ddb/child_node/node_2/3_init_data.sql:/docker-entrypoint-initdb.d/3_init_data.sql
      # - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    healthcheck:
      test: pg_isready -U postgres
    depends_on:
      - master-node

  node-3:
    <<: *node
    container_name: tbd-node-3
    ports:
      - "5435:5432"
    volumes:
      - ./ddb/child_node/node_3:/docker-entrypoint-initdb.d
    healthcheck:
      test: pg_isready -U postgres

networks:
  tbd-ddb:
    driver: bridge